# This workflow will install Python dependencies, run tests and lint
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test

on:
  push:
    branches: [ "main" ]
    paths: [ "**.py", ".github/workflows/test.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.py", ".github/workflows/test.yml" ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        python-version: ${{ matrix.python-version }}
    - run: uv pip install -e .[dev]
    - name: Test with pytest
      run: uv run --frozen pytest tests
